### PR TITLE
Add a utility function for extracting information from Magento JSON

### PR DESCRIPTION
**Pull request by DanielBrookRoberge**
This PR adds a utility function that extracts all of the information stored in JSON script tags by Magento on a page. It is not (yet) integrated with any parsers

 **JIRA**: N/A

## Changes
- Add the function

## How to test-drive this PR
- import the function into a parser and add `console.log(extractMagentoJson($html).toJS())`
- see that it logs an object with useful information on load.

### CODE REVIEW

**Comment by mikenikles** [comment]
@DanielBrookRoberge Do you mind creating a `utils-magento.js` file for that? I'd like to separate e-commerce platform specific code right from the beginning so that later, we can pull it out into a separate NPM module.

**Comment by DanielBrookRoberge** [comment]
Yes I can do that.

**Comment by mikenikles** [comment]
LGTM :+1:

**Comment by mikenikles** [comment]
LGTM :+1:

**Pull request merged**
