### PR TITLE
Disable add to cart button on PDP while an add is in progress

### PR DESCRIPTION
**Pull request by jvoll**
**JIRA**: None
**Linked PR**: https://github.com/mobify/progressive-web-sdk/pull/462

## Changes
- Before this change, when you tap "Add to Cart" on a PDP there is no indication that an add is in progress. Now, during the time that the add is happening, the "Add to Cart" button is disabled.

## How to test-drive this PR
- Add an item to the cart

### CODE REVIEW

**Comment by mikenikles** [comment]
@jvoll What's the status of this?

**Comment by jvoll** [comment]
@mikenikles we got hung up on that `npm link` stuff and then I started looking over the architecture changes so this fell off my radar. I'll get it updated tomorrow morning and just point the sdk to the other git branch it depends on I guess since we haven't go the link working just yet and then we can land this.

**Comment by jvoll** [comment]
Added "blocked" label to this so we know what's up. This PR requires SDK changes and even while pointing to the github branch of the SDK, we are still getting errors on `npm run dev` which is preventing us from trying out these SDK changes in the scaffold.

**Comment by jeremywiebe** [comment]
@jvoll I just tested this (pointing to `develop` of SDK) and it worked fine. Can we revive this and get it merged now?

**Comment by jvoll** [comment]
@jeremywiebe this is updated to the latest way of doing things and ready for review again.

**Comment by DanielBrookRoberge** [comment]
This looks good, but you've got a lint error to fix. Otherwise :+1:

**Pull request merged**
